
server:
  port: 9091
  servlet:
    context-path: /mis-productos
---

spring:
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/inventario_key
#    url: jdbc:mysql://db-bolsas-key.cuf6ai4u4jfs.us-east-1.rds.amazonaws.com:3306/inventario_key
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    username: admin
    username: root
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    password: tpM9EBgFzQ![<NTfvJu2g$6S9Ele
    password: 130594
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

clave-seguridad:
  clave: miClaveSuperSeguraDe32Caracteres

api:
#  imagenes: http://k8s-default-imagenes-65ff6abba3-120698284f8297cf.elb.us-east-1.amazonaws.com/mis-productos
#  imagenes: http://localhost:9096/mis-productos
  imagenes: https://backend-imagenes.novedades-jade.com.mx/mis-productos
  cors_angular: http://localhost:4200
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE

logging:
  level:
    root: INFO
    com.miempresa: DEBUG

guardar-imagenes:
  ruta_imagenes: D:\\Imagenes


