openapi: 3.0.1
info:
  title: API de Productos
  version: 1.0.0
  description: Documentaci칩n de la API para im치genes de productos

paths:
  /{id}/detalle/{page}/{size}:
    get:
      summary: Obtener im치genes de detalle de un producto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: page
          in: path
          required: true
          schema:
            type: integer
        - name: size
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Lista de im치genes en bytes
          content:
            application/octet-stream:
              schema:
                type: array
                items:
                  type: string
                  format: byte
        '404':
          description: Producto no encontrado
        '500':
          description: Error interno del servidor
